#!/bin/bash
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#   This file is part of the 'AndroidThreeScripts' project                  #
#   Copyright (C) 2014  'theFONZ'                                           #
#                                                                           #
#   This program is free software: you can redistribute it and/or modify    #
#   it under the terms of the GNU General Public License as published by    #
#   the Free Software Foundation, either version 2 of the License, or       #
#   any later version.                                                      #
#                                                                           #
#   This program is distributed in the hope that it will be useful,         #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of          #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                    #
#   See the GNU General Public License for more details.                    #
#                                                                           #
#   You should have received a copy of the GNU General Public license       #
#   along with this program.  If not, see 'license' in project root         #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

A3S_DIR="$( cd $( dirname ${0} )/.. && pwd )"
A3S_CONF_DIR="${A3S_DIR}/config.d"
A3S_PREFS_DIR="${A3S_DIR}/prefs"

source ${A3S_CONF_DIR}/A3S.conf    			  # Import Default Script Variables
source ${A3S_PREFS_DIR}/UserPrefs.conf    # Import User Configurable Variables

function get_time {
  TIME=$(date +"%r")
}

# remove empty lines from settings file
function Cleanup_Settings {
  sed -i '/^$/d' ${A3S_DIR}/a3s.settings
}

# basic settings file generator
function Generate_Basic_Settings {
  get_time
  printf '%s\n' "### A3S Settings File, Auto-Generated at ${TIME} ###" \
  "-----------------------------------------------------------" \
  "# Dependency Status..." \
  "Dependencies_Satisfied=false" \
  >> ${A3S_DIR}/a3s.settings
  Cleanup_Settings
}

# pass settings to a3s.settings file
function Pass_To_Settings {
  if grep -q "$Setting_Name" "$A3S_DIR/a3s.settings"; then
    sed -i '/'"${Setting_Header}"'/d' ${A3S_DIR}/a3s.settings
    sed -i '/'"${Setting_Title_Name}"'/d' ${A3S_DIR}/a3s.settings
    sed -i '/'"${Setting_Name}"'/d' ${A3S_DIR}/a3s.settings
    printf '%s\n' "${Setting_Header}" \
    "${Setting_Title_Name}=${Setting_Title_Value}" \
    "${Setting_Name}=${Setting_Value}" \
    >> ${A3S_DIR}/a3s.settings
    Cleanup_Settings
  else
    printf '%s\n' "${Setting_Header}" \
    "${Setting_Title_Name}=${Setting_Title_Value}" \
    "${Setting_Name}=${Setting_Value}" \
    >> ${A3S_DIR}/a3s.settings
    Cleanup_Settings
  fi
}
